trigger: none

pool: MyAgent

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    displayName: Build job
    
    steps:
    - task: NodeTool@0
      displayName: Setup Node.js Environment
      inputs:
        versionSpec: '16.x'

    - task: PowerShell@2
      displayName: Install Dependencies
      inputs:
        targetType: 'inline'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith'
        script: |
          npm install

    - task: PowerShell@2
      displayName: Build Application
      inputs:
        targetType: 'inline'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith'
        script: |
          npm run build

    - task: PublishPipelineArtifact@1
      displayName: Publish Build Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith/build'
        artifact: 'todo-ui'
        publishLocation: 'pipeline'



