trigger: none

pool: MyAgent

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    displayName: Build job
    
    # steps:
    # - task: NodeTool@0
    #   displayName: Setup Node.js Environment
    #   inputs:
    #     versionSpec: '16.x'

    # - task: PowerShell@2
    #   displayName: Install Dependencies
    #   inputs:
    #     targetType: 'inline'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith'
    #     script: |
    #       npm install

    # - task: PowerShell@2
    #   displayName: Build Application
    #   inputs:
    #     targetType: 'inline'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith'
    #     script: |
    #       npm run build

    # - task: PublishPipelineArtifact@1
    #   displayName: Publish Build Artifact
    #   inputs:
    #     targetPath: '$(System.DefaultWorkingDirectory)/Resourcegroupproject/Environment/ReactTodoUIMonolith/build'
    #     artifact: 'todo-ui'
    #     publishLocation: 'pipeline'
- stage: deploystage
  displayName: deploy job 
  jobs:
  - job: deploy
    displayName: deploy job
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: 'c1b81bd5-857d-4ba7-994f-2e367ce08b8a'
        pipeline: '18'
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        artifactName: 'todo-ui'
        downloadPath: '$(System.ArtifactsDirectory)'



